backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "Posts"
    label: "Posts"    
    files:
      - file: "src/pages/files/first-post.md"
        label: "first-post"
        name: "first-post"
        fields:
          - {label: "key", name: "key", widget: "hidden", default: "first-post"}
          - {label: "path", name: "path", widget: "hidden", default: "/first-post"}
          - {label: "image", name: "image", widget: "hidden", default: "/assets/post1.jpg"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "date", name: "date", widget: "datetime"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/files/second-post.md"
        label: "second-post"
        name: "second-post"
        fields:
          - {label: "key", name: "key", widget: "hidden", default: "second-post"}
          - {label: "path", name: "path", widget: "hidden", default: "/second-post"}
          - {label: "image", name: "image", widget: "hidden"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}

  - name: "Blogs"
    label: "Blogs"
    create: true
    folder: "src/pages/blog"
    slug: "{{year}}-{{month}}-{{day}}-{{time}}}{{slug}}"
    fields:
          - {label: "key", name: "key", widget: "hidden"}
          - {label: "path", name: "path", widget: "hidden", default: "/read-more"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "date", name: "date", widget: "datetime"}
          - {label: "description", name: "description", widget: "text"}
          - {label: "body", name: "body", widget: "markdown"}
          
          