backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "test_name"
    label: "test_label"
    files:
      - file: "src/files/text.md"
        label: "text-md"
        name: "text-md"
        fields:
          - {label: "title", name: "title", widget: "string"}
          - {label: "date", name : "date", widget: "date"}
          
          

        
          