backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "testfolder"
    label: "Test"
    folder: testfolder
    create: true
    fields:  
          - {label: "title", name: "title", widget: "string"}
          - {label: "date", name : "date", widget: "date"}
        
          