backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "test"
    label: "test"
    files:
      - file: "src/pages/files/text.md"
        label: "page2"
        name: "page2"
        fields:
          - {label: "title", name: "title", widget: "string"}
          - {label: "date", name : "date", widget: "date"}
          