backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "test"
    label: "test"
    files:
      - file: "src/pages/files/text.md"
        label: "text"
        name: "text"
        fields:
          - {label: "title", name: "title", widget: "string"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/files/index.md"
        label: "index"
        name: "index"
        fields:
          - {label: "title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          
          