backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/files/text.md"
        label: "page-two"
        name: "page-two"
        fields:
          - {label: "title", name: "title", widget: "string"}
          - {label: "date", name : "date", widget: "date"}
          