backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: assets

collections:
  - name: "testFolder"
    label: "testFolder"
    create: true
    files:
        label: "Test"
        name: "Test"
        fields: 
          - {label: "date", name : "date", widget: "date"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          

        
          